/**
 * Regenerates src/brand-assets.ts from the files in assets/.
 *
 * The icons have to survive a deployment that copies dist/ and nothing else,
 * which is what left the dev VM answering 500 on every icon path. Carrying
 * them as base64 inside the bundle removes the directory a deployment can
 * forget. Run after changing anything in assets/:
 *
 *   node scripts/inline-brand.mjs
 *
 * test/unit/branding.test.ts fails if the checked-in file drifts from disk.
 */
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { join } from "node:path";

const ASSETS = new URL("../assets/", import.meta.url).pathname;
const OUT = new URL("../src/brand-assets.ts", import.meta.url).pathname;

const files = readdirSync(ASSETS).filter((f) => /\.(png|svg)$/.test(f)).sort();
const entries = files.map((f) => {
  const b64 = readFileSync(join(ASSETS, f)).toString("base64");
  return `  "${f}":\n    "${b64.match(/.{1,110}/g).join('" +\n    "')}",`;
});

writeFileSync(
  OUT,
  `/**
 * The brand images, base64-encoded, generated by scripts/inline-brand.mjs.
 *
 * Do not edit by hand. These live in the bundle rather than on disk because a
 * deployment that ships dist/ without assets/ otherwise answers 500 on every
 * icon path, and the icon is what a connector list shows for this server.
 */

export const BRAND_ASSETS_BASE64: Record<string, string> = {
${entries.join("\n")}
};
`,
);
console.log(`wrote ${OUT} from ${files.length} files: ${files.join(", ")}`);
